name: stock-forecast
channels:
  - conda-forge
dependencies:
  - python=3.10.0
  - pip
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - scipy=1.13.1
  - pmdarima=2.1.1
  - statsmodels=0.14.6
  - pip:
    - yfinance==0.2.43
    - xgboost==2.1.4
    - arch==6.2.0
